### ISSUE TITLE
Documentation improvements meta-issue

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#1740]
- [x] Split "Concepts" off from "What is Feldera" into a separate top-level section (@blp)
- [ ] Improve the Getting Started section 
  - [x] In addition to docker-based instructions, add instructions to get started in the sandbox (@blp )
  - [ ] Make sure that the sandbox demo also runs in the docker form factor, so we have the same demo everywhere.  The SecOps demo can become a  "Use case" (see below).   (@snkas , @ryzhyk )
  - [x] Remove the tour and demos subsections (one of them can be moved to Use cases (see below)), replace them with a more focused demo, possibly using a series of gifs (we also discussed that it could be a video, but that may not be the best format) showing how to build a simple pipeline in the UI. This demo should probably be based on the sandbox demo and should be designed to illustrate the Concepts (@blp)
- [ ] Improved REST API reference (@snkas )
  - [ ] https://github.com/feldera/website/issues/509
  - [ ] Add an overview section, explaining the high-level structure of the API with references to relevant sections
  - [ ] Go through individual endpoint docs and make sure they are correct and have useful examples.
- [x] Complete connector documentation 
  - [x] Improve Kafka and HTTP connector docs (@snkas )
  - [x] Document Delta table connector (@ryzhyk ) https://github.com/feldera/feldera/pull/1820
- [x] Python API documentation (@abhizer)
- [x] Add a Use Cases section.  The first two use cases may be SecOps and the fraud detection real-time ML demo. The SecOps use case can be adapted from the existing demo page + the youtube video we just published. (@ryzhyk )
- [ ] Add a section on DBSP. Collect the various resources we have for DBSP: papers, talks, blogs, code, so we can easily refer people to it. @mihaibudiu 

The final doc structure will look something like

- What is Feldera
- Concepts with video/GIFs
- Getting started
  - docker
  - sandbox
- Deploy
  - Docker
  - Feldera enterprise
- Tutorials
  - UI
  - API
- Use cases
  - Real-time feature engineering (notebook)
  - SecOps
- References
  - API reference
  - Connectors (transport)
  - Formats
  - Python API
  - SQL reference

**Comment by lalithsuresh** [comment]
There are different docusaurus plugins that can render better OpenAPI docs. It's worth considering them -- I tried a few times but I don't know any JS, which makes it hard to debug.

**Comment by blp** [comment]
I did some preliminary rearranging: https://github.com/feldera/feldera/pull/1754

**Comment by blp** [comment]
I added GIFs showing off our concepts: https://github.com/feldera/feldera/pull/1763

**Comment by snkas** [comment]
Connectors docs done in: https://github.com/feldera/feldera/pull/1746

**Comment by blp** [comment]
Unassigned myself because I think I finished what I was asked to do. Feel free to reassign me if more gets added or if I missed something.

**Comment by lalithsuresh** [comment]
@ryzhyk could you move to the next sprint and assign todos as relevant?

**Comment by lalithsuresh** [comment]
@ryzhyk is this issue good to close?
