### ISSUE TITLE
Python API todos

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1776]
- [x] Publish docs on the website
- [x] Add a `foreach_chunk` method for streaming HTTP output - https://github.com/feldera/feldera/pull/1792
- [x] Pass the new `backpressure` flag to the output HTTP connector to prevent it from dropping chunks. Alternatively, make this flag configurable, but the default for the Python API should be true. - https://github.com/feldera/feldera/pull/1791
- [x] Kafka connector support - https://github.com/feldera/feldera/pull/1807
- [x] HTTP get connector support ([docs](https://www.feldera.com/docs/connectors/sources/http-get/)) - https://github.com/feldera/feldera/pull/1816
- [x] Run Python SDK tests in ci. - https://github.com/feldera/feldera/pull/1873
- [x] The input HTTP connector should split large inputs into multiple HTTP requests. #1846 
- [x] Pipeline state management / tracking 
- [x] Allow feeding new input data frames at runtime #1872 
- [x] `wait_for_completion` - wait for a running pipeline to complete #1872 
- [x] #1851 introduced local views. We need to add support for them in the Python SDK, probably in the form of a `register_local_view` method.  I would go a step farther and rename `register_view` to `register_output_view`, so that users must make an explicit choice to expose the view externally.
- [x] Improve auto-generated docs structure. Is it possible to flatten the docs so that the main page includes the intro section and  `feldera` package docs inlined? The `feldera.rest` subpackage on the other hand could live in a separate page so that it doesn't get in the way of browsing the frontend API? - https://github.com/feldera/feldera/pull/1942

Post-API-refactoring tasks:
- [ ] Interact with the backend to maintain the state of the program: rather than tracking tables and views locally, the Python SDK should forward all register_view/register_table requests to the backend and get back validation results and updated program schema.  In addition to providing instant feedback about invalid SQL, this will allow the API to accept arbitrary chunks of SQL code (e.g., multiple table/view declarations). This requires changes to the backend.  
- [ ] Delta input/output connectors: implement builder pattern similar to other connectors, document connector config with examples.
- [ ] Output buffer config.  Once we switch to using the builder pattern for all connectors, add methods to [configure the output buffer](https://github.com/feldera/feldera/blob/e6b96ddad5808ae0469eb8cdd30967cf5beb8393/crates/pipeline-types/src/config.rs#L259) for all of them.
- [ ] Support for schema inference from Delta tables

**Comment by abhizer** [comment]
- [ ] After the `backpressure` PR (#1791) is merged, update `foreach_chunk` docs (#1792) to say that the callback shouldn't block

**Comment by abhizer** [comment]
- [ ] add a mechanism to push series of batches via dataframes to a running pipeline

**Comment by ryzhyk** [comment]
Closing, since the remaining todos are no longer relevant with the new API
