### ISSUE TITLE
Refactor demos

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#2186]
**Tasks:**
- [x] SQL comment preamble for metadata
- [x] Refactor the simplest of demos to just use a single SQL file using the preamble
- [x] Include demos automatically in image builds such that the welcome screen is not empty

**SQL comment preamble for metadata**
Rather than having metadata be explicitly set in a demo, we can define it within the SQL comments. This will make SQL self-contained.

For example:
```sql
-- name: example
-- title: Example
-- description: This is an example description.

CREATE TABLE ... (rest of the program)
```

**Comment by mihaibudiu** [comment]
May not be easy if the parser throws away SQL comments.

**Comment by snkas** [comment]
It will not be using the SQL compiler for this, just straightforward pattern find at the UI side (it is just the demos being served from the demo endpoint)

**Comment by lalithsuresh** [comment]
@snkas we can iteratively improve this to also produce all the use cases on the website.

**Comment by snkas** [comment]
This includes simplifying in general how to define demos.
