### ISSUE TITLE
[RFC] Make `Catalog` API case-insensitive.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#51]
I am working on a PR for this and would like to discuss the exact semantics we want to support here.

## Background

`Catalog` is the data structure used by the `adapters` crate to lookup input/output streams of a circuit by name when:

- Instantiating input/output connectors from the yaml pipeline config.
- Handling HTTP ingress/egress requests.

At the moment the lookup is case sensitive, which means that user-provided stream names must match the case of compiler-generated table names.  The compiler capitalizes table names, except for tables declared with quotes, whose case is preserved.  So whether the table is declared as `table Foo`, `table foo`, or `table FOO`, the user must refer to it as `/ingress/FOO`.

## Design discussion

A simple solution is to make all lookups case-insensitive, so that `/ingress/foo`, `/ingress/FOO`, `/ingress/Foo` are all accepted.

Question is whether this is adequate for case-sensitive tables, i.e., tables declared with quotes: `create table "FoO"`.  Two potential concerns here are:
1. Is it ok to be permissive and recognize these table names in the "wrong" case?
2. A more important concern is name clashes.  At the moment the compiler will accept the following SQL:
  ```sql
  create table "Vendor" (...);
  create table "VENDOR"(...);
  create table vendor (...);
  ```
  In the SQL code, the compiler is able to distinguish these three tables because case-sensitive names must always be quoted, so the user must write `select * from "Vendor"`, `select * from "VENDOR"`, `select * from vendor` to refer to them respectively.  If we want to support this in the rest of Feldera, we will will need to do the same in our HTTP API and yaml, so the user will have to use  `/ingress/"Vendor"`, `/ingress/"VENDOR"`, and `/ingress/vendor` for these tables respectively.

  This will require the following changes to Feldera:

- the SQL compiler will have to pass a case sensitivity flag to the catalog (e.g., as a Boolean flag or by specifying the table name in quotes)
  - UPDATE: instead of adding the flag, the SQL compiler will pass case-sensitive table names in quotes, precisely as they appear in the SQL code.
- the catalog will match table names taking into account the case sensitivity attribute
- the pipeline manager and the pipeline runner will support `ingress`/`egress` URLs with quotes (not sure if this requires any additional work).
- the pipeline runner must additionally support quoted table names in yaml.
- the UI must use case sensitivity information already available in the JSON schema generated by the compiler to display case-sensitive table names in quotes.
  - UPDATE: the SQL compiler should also emit quoted table names in schema.json. We will test if this is enough for the UI to do the right thing or if additional UI changes will be needed

@mihaibudiu , @lalithsuresh , @snkas , @gz , @mohsinbeg, @Karakatiza666 

## Implementation plan

- [ ] Modify the SQL compiler to pass case-sensitive table/view names in quotes to the catalog and to `schema.json`. @mihaibudiu 
- [ ] Modify the `adapters` crate to correctly account for case sensitivity.  @ryzhyk 
- [ ] Add integrations tests to the pipeline manager (and/or modify extend existing tests) to make sure that the manager can handle case-sensitive names end-to-end. @ryzhyk 
- [ ] Fixup the UI to support quoted table names if needed and add UI tests @Karakatiza666

**Comment by blp** [comment]
TIL that names in SQL are *sometimes* case sensitive. Ugh, who designed this language?

**Comment by lalithsuresh** [comment]
We can use escape characters to refer to quoted names in the REST API if required. It's not pretty but it'll be quite consistent. So an unquoted name in the REST API will default to case-insensitive matches, and quoted names will expect an exact match.

**Comment by ryzhyk** [comment]
@lalithsuresh , what will the `/ingress` URL look like for a case-sensitive table name?

**Comment by ryzhyk** [comment]
But yes, by making quotes part of the name we should be able to eliminate all ambiguities, unless I am missing something.

**Comment by lalithsuresh** [comment]
Yup, I think it should remove all ambiguities. The ingress URL will be `/ingress/{%22Vendor%22, %22VENDOR%22, vendor/VeNdor}`.

**Comment by mihaibudiu** [comment]
I plan to make the compiler changes after the Rust libraries are ready to accept them.
